### ISSUE TITLE
v1.5.3+ is broken

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [AM2R-Community-Developers/AM2R-Autopatcher-Windows#3]
Starting with v1.5.3 the patcher no longer works.

```
Patching AM2R.exe...
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent

Patching failed!
Aborting patching process.
This patch applies ONLY to v1.1 of AM2R.
```
v1.5.2 works fine with the same AM2R_11.zip

Sure, AM2RLauncher exists, but it can't patch AM2R_11 without internet connection, so it's not a proper replacement for AM2R-Autopatcher.

**Comment by Lojemiru** [comment]
Known. We changed the game patching method with a different compiler and haven't had the time to adjust the patch application process yet.

**Comment by Miepee** [comment]
> Sure, AM2RLauncher exists, but it can't patch AM2R_11 without internet connection, so it's not a proper replacement for AM2R-Autopatcher.

AM2RLauncher is able to patch without internet. It only drops a warning that you will not receive updates, but you can still patch without problems (assuming you were able to download the newer patch files before once).

**Comment by nbmrjuhneibkr** [comment]
>AM2RLauncher is able to patch without internet. It only drops a warning that you will not receive updates, but you can still patch without problems (assuming you were able to download the newer patch files before once).

I don't think this can be done just by using original unaltered files from GitHub. I tried putting AM2R-Autopatcher files in AM2RLauncher\PatchData\ manually - and it gave me all sorts of errors when I started it without internet. This means that currently the only way to patch AM2R offline is by using a pre-configured copy of AM2RLauncher that has been previously used on a system with internet access at least once.

**Comment by Miepee** [comment]
You need internet either way. To either download the contents of this repo, or to let the AM2RLauncher do a git pull to update its copy. Since we don't distribute the patch files by mail or any other offline way, you *have* to have an internet connection to get them.
Also, please don't replace or tamper with the PatchData directory. If you want to update it without the GUI, you can just open a terminal in that folder and use `git pull`.

**Comment by nbmrjuhneibkr** [comment]
My point is that there should be a way to use the software without relying on any online services as soon as I download AM2RLauncher and AM2R-Autopatcher-Windows - even decades from now, when GitHub infrastructure may no longer exist.
Right now any kind of preservation is not possible without starting the launcher and letting it connect to GitHub first.

**Comment by Miepee** [comment]
It doesn't connect to Github for patching though, only to check if new updates exist. You need *any* kind of online connection for that, there's no way around it.
And yes, preservation is possible. Since every user of the AM2RLauncher has a local git repo, which tracks every change that has happened. So in a way, every user is already preserving it. If our git repos would die(i.e. github and gitlab site with the patchfiles) any of our few thousand users could just reupload the git repo to somewhere else.

**Comment by nbmrjuhneibkr** [comment]
Let me repeat: I want to be able to download all the necessary files just by using a regular web browser, store them wherever I want (without having to launch anything first), and then still be able to get them working at some point in the future, when certain online services may be unreachable.
There's no (easy) way to do this with AM2RLauncher. AM2R-Autopatcher can do this perfectly - but it doesn't work right now. Which is why I submitted this issue in the first place.

**Comment by Miepee** [comment]
Autopatcher is still broken, but other news.
You can now download the Patchdata-vX.zip from the release page here, and use the PatchData folder inside for the AM2RLauncher. If you then disable the automatic updates from the AM2RLauncher, you'll have a way for this to work for the future as well.

**Comment by nbmrjuhneibkr** [comment]
Thanks.
I also realized that I can just copy new files and apply xdelta patches manually (at least for Windows build), without the need to rely on AM2RLauncher.

AM2R-Autopatcher is convenient because it's standalone, offline and fully automated. I understand that broken autopatcher script may not be a high-priority bug, but I still hope that it will be fixed eventually.

**Comment by Lojemiru** [comment]
Autopatcher script fixed. Apologies for the delay.
